import type { Position } from './squads';

export interface LineupPlayer {
  name: string;
  number: number;
  position: Position;
  club: string;
}

export interface TeamLineup {
  starters: LineupPlayer[];
  subs: LineupPlayer[];
}

export interface MatchLineup {
  home: TeamLineup;
  away: TeamLineup;
}

export const LINEUPS: Record<string, MatchLineup> = {
  'fifwc-usa-par-2026-06-12': {
    home: {
      starters: [
        { name: 'Matt Turner', number: 1, position: 'GK', club: 'New England Revolution' },
        { name: 'Sergino Dest', number: 2, position: 'DEF', club: 'PSV' },
        { name: 'Chris Richards', number: 6, position: 'DEF', club: 'Crystal Palace' },
        { name: 'Miles Robinson', number: 4, position: 'DEF', club: 'FC Cincinnati' },
        { name: 'Antonee Robinson', number: 3, position: 'DEF', club: 'Fulham' },
        { name: 'Tyler Adams', number: 8, position: 'MID', club: 'Bournemouth' },
        { name: 'Weston McKennie', number: 7, position: 'MID', club: 'Juventus' },
        { name: 'Tim Weah', number: 18, position: 'FWD', club: 'Marseille' },
        { name: 'Gio Reyna', number: 10, position: 'MID', club: 'Borussia Mönchengladbach' },
        { name: 'Christian Pulisic', number: 26, position: 'FWD', club: 'AC Milan' },
        { name: 'Folarin Balogun', number: 9, position: 'FWD', club: 'Monaco' },
      ],
      subs: [
        { name: 'Chris Brady', number: 12, position: 'GK', club: 'Chicago Fire' },
        { name: 'Matt Freese', number: 23, position: 'GK', club: 'New York City FC' },
        { name: 'Joe Scally', number: 16, position: 'DEF', club: 'Borussia Mönchengladbach' },
        { name: 'Auston Trusty', number: 19, position: 'DEF', club: 'Celtic' },
        { name: 'Mark McKenzie', number: 15, position: 'DEF', club: 'Toulouse' },
        { name: 'Malik Tillman', number: 14, position: 'MID', club: 'Bayer Leverkusen' },
        { name: 'Cristian Roldan', number: 17, position: 'MID', club: 'Seattle Sounders' },
        { name: 'Brenden Aaronson', number: 11, position: 'FWD', club: 'Leeds United' },
        { name: 'Ricardo Pepi', number: 13, position: 'FWD', club: 'PSV' },
        { name: 'Haji Wright', number: 24, position: 'FWD', club: 'Coventry City' },
        { name: 'Alejandro Zendejas', number: 25, position: 'FWD', club: 'Club América' },
      ],
    },
    away: {
      starters: [
        { name: 'Julio González', number: 1, position: 'GK', club: 'Olimpia' },
        { name: 'Mathías Villasanti', number: 2, position: 'DEF', club: 'Grêmio' },
        { name: 'Fabian Balbuena', number: 5, position: 'DEF', club: 'Club América' },
        { name: 'Junior Alonso', number: 4, position: 'DEF', club: 'Atlético San Luis' },
        { name: 'Santiago Arzamendia', number: 3, position: 'DEF', club: 'Celta Vigo' },
        { name: 'Richard Sánchez', number: 6, position: 'MID', club: 'Tigres UANL' },
        { name: 'Gastón Giménez', number: 8, position: 'MID', club: 'FC Juárez' },
        { name: 'Ángel Romero', number: 17, position: 'FWD', club: 'Club América' },
        { name: 'Miguel Almirón', number: 10, position: 'MID', club: 'Newcastle United' },
        { name: 'Alejandro Romero Gamarra', number: 11, position: 'FWD', club: 'Cerro Porteño' },
        { name: 'Julio Enciso', number: 9, position: 'FWD', club: 'Brighton' },
      ],
      subs: [
        { name: 'Carlos Coronel', number: 12, position: 'GK', club: 'New York Red Bulls' },
        { name: 'Omar Alderete', number: 15, position: 'DEF', club: 'Getafe' },
        { name: 'Gustavo Gómez', number: 14, position: 'DEF', club: 'Palmeiras' },
        { name: 'Blas Riveros', number: 16, position: 'DEF', club: 'Borussia Mönchengladbach' },
        { name: 'Rodrigo Rojas', number: 7, position: 'MID', club: 'Racing Club' },
        { name: 'Andrés Cubas', number: 13, position: 'MID', club: 'Lens' },
        { name: 'Diego Gómez', number: 19, position: 'MID', club: 'Inter Miami' },
        { name: 'Jorge Morel', number: 18, position: 'FWD', club: 'Independiente' },
        { name: 'Robert Morales', number: 20, position: 'FWD', club: 'Olimpia' },
      ],
    },
  },

  'fifwc-bra-mar-2026-06-13': {
    home: {
      starters: [
        { name: 'Alisson', number: 1, position: 'GK', club: 'Liverpool' },
        { name: 'Danilo', number: 2, position: 'DEF', club: 'Flamengo' },
        { name: 'Marquinhos', number: 4, position: 'DEF', club: 'PSG' },
        { name: 'Gabriel', number: 5, position: 'DEF', club: 'Arsenal' },
        { name: 'Alex Sandro', number: 3, position: 'DEF', club: 'Flamengo' },
        { name: 'Casemiro', number: 8, position: 'MID', club: 'Manchester United' },
        { name: 'Lucas Paquetá', number: 7, position: 'MID', club: 'Flamengo' },
        { name: 'Raphinha', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Neymar', number: 9, position: 'FWD', club: 'Santos' },
        { name: 'Vinicius Jr.', number: 10, position: 'FWD', club: 'Real Madrid' },
        { name: 'Endrick', number: 24, position: 'FWD', club: 'Real Madrid' },
      ],
      subs: [
        { name: 'Ederson', number: 12, position: 'GK', club: 'Fenerbahçe' },
        { name: 'Weverton', number: 23, position: 'GK', club: 'Grêmio' },
        { name: 'Ibañez', number: 14, position: 'DEF', club: 'Al Ahli' },
        { name: 'Léo Pereira', number: 13, position: 'DEF', club: 'Flamengo' },
        { name: 'Douglas Santos', number: 22, position: 'DEF', club: 'Zenit' },
        { name: 'Bruno Guimarães', number: 16, position: 'MID', club: 'Newcastle United' },
        { name: 'Fabinho', number: 15, position: 'MID', club: 'Al Ittihad' },
        { name: 'Gabriel Martinelli', number: 18, position: 'FWD', club: 'Arsenal' },
        { name: 'Matheus Cunha', number: 20, position: 'FWD', club: 'Manchester United' },
        { name: 'Luiz Henrique', number: 19, position: 'FWD', club: 'Zenit' },
      ],
    },
    away: {
      starters: [
        { name: 'Yassine Bounou', number: 1, position: 'GK', club: 'Fenerbahçe' },
        { name: 'Achraf Hakimi', number: 2, position: 'DEF', club: 'PSG' },
        { name: 'Nayef Aguerd', number: 5, position: 'DEF', club: 'West Ham' },
        { name: 'Romain Saïss', number: 6, position: 'DEF', club: 'Besiktas' },
        { name: 'Noussair Mazraoui', number: 3, position: 'DEF', club: 'Manchester United' },
        { name: 'Sofyan Amrabat', number: 4, position: 'MID', club: 'Marseille' },
        { name: 'Azzedine Ounahi', number: 8, position: 'MID', club: 'Marseille' },
        { name: 'Bilal El Khannouss', number: 10, position: 'MID', club: 'Leicester City' },
        { name: 'Hakim Ziyech', number: 7, position: 'FWD', club: 'Galatasaray' },
        { name: 'Youssef En-Nesyri', number: 9, position: 'FWD', club: 'Fenerbahçe' },
        { name: 'Soufiane Boufal', number: 11, position: 'FWD', club: 'Angers' },
      ],
      subs: [
        { name: 'Ahmed Reda Tagnaouti', number: 16, position: 'GK', club: 'Wydad AC' },
        { name: 'Munir Mohamedi', number: 23, position: 'GK', club: 'Málaga' },
        { name: 'Yahia Attiyat Allah', number: 15, position: 'DEF', club: 'Wydad AC' },
        { name: 'Adam Masina', number: 14, position: 'DEF', club: 'Udinese' },
        { name: 'Jawad El Yamiq', number: 13, position: 'DEF', club: 'Real Valladolid' },
        { name: 'Selim Amallah', number: 17, position: 'MID', club: 'Standard Liège' },
        { name: 'Zakaria Aboukhlal', number: 19, position: 'MID', club: 'Toulouse' },
        { name: 'Ayoub El Kaabi', number: 18, position: 'FWD', club: 'Olympiacos' },
        { name: 'Abde Ezzalzouli', number: 20, position: 'FWD', club: 'Real Betis' },
        { name: 'Ryan Mmaee', number: 22, position: 'FWD', club: 'Ferencváros' },
      ],
    },
  },

  'fifwc-esp-cvi-2026-06-15': {
    home: {
      starters: [
        { name: 'Unai Simón', number: 1, position: 'GK', club: 'Athletic Club' },
        { name: 'Pedro Porro', number: 2, position: 'DEF', club: 'Tottenham' },
        { name: 'Pau Cubarsí', number: 4, position: 'DEF', club: 'Barcelona' },
        { name: 'Aymeric Laporte', number: 5, position: 'DEF', club: 'Athletic Club' },
        { name: 'Marc Cucurella', number: 19, position: 'DEF', club: 'Chelsea' },
        { name: 'Rodri', number: 14, position: 'MID', club: 'Manchester City' },
        { name: 'Pedri', number: 7, position: 'MID', club: 'Barcelona' },
        { name: 'Fabián Ruiz', number: 8, position: 'MID', club: 'PSG' },
        { name: 'Lamine Yamal', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Mikel Oyarzabal', number: 13, position: 'FWD', club: 'Real Sociedad' },
        { name: 'Nico Williams', number: 17, position: 'FWD', club: 'Athletic Club' },
      ],
      subs: [
        { name: 'David Raya', number: 12, position: 'GK', club: 'Arsenal' },
        { name: 'Joan García', number: 23, position: 'GK', club: 'Barcelona' },
        { name: 'Alejandro Grimaldo', number: 3, position: 'DEF', club: 'Bayer Leverkusen' },
        { name: 'Eric García', number: 16, position: 'DEF', club: 'Barcelona' },
        { name: 'Marc Pubill', number: 24, position: 'DEF', club: 'Atlético Madrid' },
        { name: 'Gavi', number: 9, position: 'MID', club: 'Barcelona' },
        { name: 'Mikel Merino', number: 15, position: 'MID', club: 'Arsenal' },
        { name: 'Martin Zubimendi', number: 20, position: 'MID', club: 'Arsenal' },
        { name: 'Dani Olmo', number: 10, position: 'FWD', club: 'Barcelona' },
        { name: 'Ferran Torres', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Yeremy Pino', number: 25, position: 'FWD', club: 'Crystal Palace' },
      ],
    },
    away: {
      starters: [
        { name: 'Vozinha', number: 1, position: 'GK', club: 'Gil Vicente' },
        { name: 'Odair Fortes', number: 2, position: 'DEF', club: 'Casa Pia' },
        { name: 'Roberto Lopes', number: 5, position: 'DEF', club: 'Shamrock Rovers' },
        { name: 'Marco Moreno', number: 4, position: 'DEF', club: 'Marítimo' },
        { name: 'Dylan Tavares', number: 3, position: 'DEF', club: 'Benfica' },
        { name: 'Jamiro Monteiro', number: 8, position: 'MID', club: 'New England Revolution' },
        { name: 'Lisandro Semedo', number: 6, position: 'MID', club: 'Deportivo La Coruña' },
        { name: 'Garry Rodrigues', number: 7, position: 'FWD', club: 'Galatasaray' },
        { name: 'Júnior Tavares', number: 11, position: 'FWD', club: 'Benfica' },
        { name: 'Djaniny', number: 9, position: 'FWD', club: 'Al-Qadisiyah' },
        { name: 'Kenny Rocha Santos', number: 10, position: 'MID', club: 'Gil Vicente' },
      ],
      subs: [
        { name: 'Xico Fati', number: 12, position: 'GK', club: 'CD Feirense' },
        { name: 'Stopira', number: 13, position: 'DEF', club: 'HNK Rijeka' },
        { name: 'João Almada', number: 14, position: 'DEF', club: 'Videoton' },
        { name: 'Steven Fortes', number: 15, position: 'MID', club: 'Vitória SC' },
        { name: 'Ryan Mendes', number: 16, position: 'FWD', club: 'Standard Liège' },
        { name: 'Cláudio Winck', number: 17, position: 'DEF', club: 'Famalicão' },
        { name: 'Bebé', number: 18, position: 'FWD', club: 'UD Las Palmas' },
      ],
    },
  },

  'fifwc-eng-cro-2026-06-17': {
    home: {
      starters: [
        { name: 'Jordan Pickford', number: 1, position: 'GK', club: 'Everton' },
        { name: 'Reece James', number: 2, position: 'DEF', club: 'Chelsea' },
        { name: 'John Stones', number: 4, position: 'DEF', club: 'Manchester City' },
        { name: 'Marc Guéhi', number: 5, position: 'DEF', club: 'Manchester City' },
        { name: 'Tino Livramento', number: 22, position: 'DEF', club: 'Newcastle United' },
        { name: 'Declan Rice', number: 8, position: 'MID', club: 'Arsenal' },
        { name: 'Kobbie Mainoo', number: 14, position: 'MID', club: 'Manchester United' },
        { name: 'Bukayo Saka', number: 11, position: 'FWD', club: 'Arsenal' },
        { name: 'Jude Bellingham', number: 7, position: 'MID', club: 'Real Madrid' },
        { name: 'Marcus Rashford', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Harry Kane', number: 9, position: 'FWD', club: 'Bayern Munich' },
      ],
      subs: [
        { name: 'Dean Henderson', number: 12, position: 'GK', club: 'Crystal Palace' },
        { name: 'James Trafford', number: 23, position: 'GK', club: 'Manchester City' },
        { name: 'Dan Burn', number: 3, position: 'DEF', club: 'Newcastle United' },
        { name: 'Ezri Konsa', number: 6, position: 'DEF', club: 'Aston Villa' },
        { name: 'Djed Spence', number: 16, position: 'DEF', club: 'Tottenham' },
        { name: 'Eberechi Eze', number: 10, position: 'MID', club: 'Arsenal' },
        { name: 'Jordan Henderson', number: 19, position: 'MID', club: 'Brentford' },
        { name: 'Elliot Anderson', number: 15, position: 'MID', club: 'Nottingham Forest' },
        { name: 'Ollie Watkins', number: 21, position: 'FWD', club: 'Aston Villa' },
        { name: 'Anthony Gordon', number: 25, position: 'FWD', club: 'Barcelona' },
        { name: 'Noni Madueke', number: 26, position: 'FWD', club: 'Arsenal' },
      ],
    },
    away: {
      starters: [
        { name: 'Dominik Livaković', number: 1, position: 'GK', club: 'Trabzonspor' },
        { name: 'Josip Stanišić', number: 2, position: 'DEF', club: 'Bayer Leverkusen' },
        { name: 'Joško Gvardiol', number: 6, position: 'DEF', club: 'Manchester City' },
        { name: 'Martin Erlić', number: 5, position: 'DEF', club: 'Sassuolo' },
        { name: 'Borna Sosa', number: 3, position: 'DEF', club: 'Ajax' },
        { name: 'Marcelo Brozović', number: 11, position: 'MID', club: 'Al Nassr' },
        { name: 'Luka Modrić', number: 10, position: 'MID', club: 'Real Madrid' },
        { name: 'Mateo Kovačić', number: 8, position: 'MID', club: 'Manchester City' },
        { name: 'Ivan Perišić', number: 4, position: 'FWD', club: 'Hajduk Split' },
        { name: 'Andrej Kramarić', number: 9, position: 'FWD', club: 'Hoffenheim' },
        { name: 'Lovro Majer', number: 7, position: 'FWD', club: 'Real Sociedad' },
      ],
      subs: [
        { name: 'Ivo Grbić', number: 23, position: 'GK', club: 'Atlético Madrid' },
        { name: 'Nediljko Labrović', number: 12, position: 'GK', club: 'Hajduk Split' },
        { name: 'Borna Barišić', number: 13, position: 'DEF', club: 'Rangers' },
        { name: 'Dario Španić', number: 15, position: 'DEF', club: 'Hajduk Split' },
        { name: 'Luka Sučić', number: 17, position: 'MID', club: 'Red Bull Salzburg' },
        { name: 'Mario Pašalić', number: 18, position: 'MID', club: 'Atalanta' },
        { name: 'Petar Sučić', number: 19, position: 'MID', club: 'Dinamo Zagreb' },
        { name: 'Bruno Petković', number: 16, position: 'FWD', club: 'Dinamo Zagreb' },
        { name: 'Marko Livaja', number: 20, position: 'FWD', club: 'Hajduk Split' },
        { name: 'Mislav Oršić', number: 21, position: 'FWD', club: 'Club Brugge' },
      ],
    },
  },

  'fifwc-usa-aus-2026-06-19': {
    home: {
      starters: [
        { name: 'Matt Turner', number: 1, position: 'GK', club: 'New England Revolution' },
        { name: 'Sergino Dest', number: 2, position: 'DEF', club: 'PSV' },
        { name: 'Chris Richards', number: 6, position: 'DEF', club: 'Crystal Palace' },
        { name: 'Miles Robinson', number: 4, position: 'DEF', club: 'FC Cincinnati' },
        { name: 'Antonee Robinson', number: 3, position: 'DEF', club: 'Fulham' },
        { name: 'Tyler Adams', number: 8, position: 'MID', club: 'Bournemouth' },
        { name: 'Weston McKennie', number: 7, position: 'MID', club: 'Juventus' },
        { name: 'Malik Tillman', number: 14, position: 'MID', club: 'Bayer Leverkusen' },
        { name: 'Christian Pulisic', number: 26, position: 'FWD', club: 'AC Milan' },
        { name: 'Gio Reyna', number: 10, position: 'MID', club: 'Borussia Mönchengladbach' },
        { name: 'Folarin Balogun', number: 9, position: 'FWD', club: 'Monaco' },
      ],
      subs: [
        { name: 'Chris Brady', number: 12, position: 'GK', club: 'Chicago Fire' },
        { name: 'Matt Freese', number: 23, position: 'GK', club: 'New York City FC' },
        { name: 'Joe Scally', number: 16, position: 'DEF', club: 'Borussia Mönchengladbach' },
        { name: 'Mark McKenzie', number: 15, position: 'DEF', club: 'Toulouse' },
        { name: 'Auston Trusty', number: 19, position: 'DEF', club: 'Celtic' },
        { name: 'Cristian Roldan', number: 17, position: 'MID', club: 'Seattle Sounders' },
        { name: 'Sebastian Berhalter', number: 22, position: 'MID', club: 'Vancouver Whitecaps' },
        { name: 'Tim Weah', number: 18, position: 'FWD', club: 'Marseille' },
        { name: 'Brenden Aaronson', number: 11, position: 'FWD', club: 'Leeds United' },
        { name: 'Ricardo Pepi', number: 13, position: 'FWD', club: 'PSV' },
        { name: 'Haji Wright', number: 24, position: 'FWD', club: 'Coventry City' },
      ],
    },
    away: {
      starters: [
        { name: 'Mathew Ryan', number: 1, position: 'GK', club: 'FC Copenhagen' },
        { name: 'Nathaniel Atkinson', number: 2, position: 'DEF', club: 'Hearts' },
        { name: 'Harry Souttar', number: 5, position: 'DEF', club: 'Leicester City' },
        { name: 'Kye Rowles', number: 4, position: 'DEF', club: 'Hearts' },
        { name: 'Joel King', number: 3, position: 'DEF', club: 'Ipswich Town' },
        { name: 'Jackson Irvine', number: 8, position: 'MID', club: 'St. Pauli' },
        { name: 'Riley McGree', number: 10, position: 'MID', club: 'Middlesbrough' },
        { name: 'Aaron Mooy', number: 6, position: 'MID', club: 'Celtic' },
        { name: 'Mathew Leckie', number: 7, position: 'FWD', club: 'Melbourne City' },
        { name: 'Mitchell Duke', number: 9, position: 'FWD', club: 'Fagiano Okayama' },
        { name: 'Craig Goodwin', number: 11, position: 'FWD', club: 'Adelaide United' },
      ],
      subs: [
        { name: 'Joe Gauci', number: 12, position: 'GK', club: 'Adelaide United' },
        { name: 'Andrew Redmayne', number: 23, position: 'GK', club: 'Sydney FC' },
        { name: 'Miloš Degenek', number: 14, position: 'DEF', club: 'Columbus Crew' },
        { name: 'Lewis Miller', number: 15, position: 'DEF', club: 'Middlesbrough' },
        { name: 'Thomas Deng', number: 16, position: 'DEF', club: 'Al Ain' },
        { name: 'Keanu Baccus', number: 17, position: 'MID', club: 'St. Mirren' },
        { name: 'Denis Genreau', number: 18, position: 'MID', club: 'Toulouse' },
        { name: 'Awer Mabil', number: 19, position: 'FWD', club: 'Cadiz' },
        { name: 'Kusini Yengi', number: 20, position: 'FWD', club: 'Adelaide United' },
        { name: 'Adam Taggart', number: 21, position: 'FWD', club: 'Cerezo Osaka' },
      ],
    },
  },

  'fifwc-bra-hai-2026-06-19': {
    home: {
      starters: [
        { name: 'Alisson', number: 1, position: 'GK', club: 'Liverpool' },
        { name: 'Danilo', number: 2, position: 'DEF', club: 'Flamengo' },
        { name: 'Marquinhos', number: 4, position: 'DEF', club: 'PSG' },
        { name: 'Gabriel', number: 5, position: 'DEF', club: 'Arsenal' },
        { name: 'Alex Sandro', number: 3, position: 'DEF', club: 'Flamengo' },
        { name: 'Casemiro', number: 8, position: 'MID', club: 'Manchester United' },
        { name: 'Bruno Guimarães', number: 16, position: 'MID', club: 'Newcastle United' },
        { name: 'Raphinha', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Neymar', number: 9, position: 'FWD', club: 'Santos' },
        { name: 'Vinicius Jr.', number: 10, position: 'FWD', club: 'Real Madrid' },
        { name: 'Matheus Cunha', number: 20, position: 'FWD', club: 'Manchester United' },
      ],
      subs: [
        { name: 'Ederson', number: 12, position: 'GK', club: 'Fenerbahçe' },
        { name: 'Weverton', number: 23, position: 'GK', club: 'Grêmio' },
        { name: 'Bremer', number: 6, position: 'DEF', club: 'Juventus' },
        { name: 'Léo Pereira', number: 13, position: 'DEF', club: 'Flamengo' },
        { name: 'Ibañez', number: 14, position: 'DEF', club: 'Al Ahli' },
        { name: 'Lucas Paquetá', number: 7, position: 'MID', club: 'Flamengo' },
        { name: 'Fabinho', number: 15, position: 'MID', club: 'Al Ittihad' },
        { name: 'Gabriel Martinelli', number: 18, position: 'FWD', club: 'Arsenal' },
        { name: 'Endrick', number: 24, position: 'FWD', club: 'Real Madrid' },
        { name: 'Luiz Henrique', number: 19, position: 'FWD', club: 'Zenit' },
      ],
    },
    away: {
      starters: [
        { name: 'Josué Duverger', number: 1, position: 'GK', club: 'Cibao FC' },
        { name: 'Frantzdy Pierrot', number: 2, position: 'DEF', club: 'Livingston' },
        { name: 'Andrew Jean-Baptiste', number: 5, position: 'DEF', club: 'Beitar Jerusalem' },
        { name: 'Wilde-Donald Guerrier', number: 4, position: 'DEF', club: 'Ferencváros' },
        { name: 'Mechack Jérome', number: 3, position: 'DEF', club: 'Vancouver Whitecaps' },
        { name: 'Derrick Étienne', number: 8, position: 'MID', club: 'Columbus Crew' },
        { name: 'Rémy Edmilson', number: 6, position: 'MID', club: 'Valenciennes' },
        { name: 'Duckens Nazon', number: 7, position: 'FWD', club: 'Wigan Athletic' },
        { name: 'Steeven Saba', number: 10, position: 'MID', club: 'Valenciennes' },
        { name: 'Gaël Métayer', number: 11, position: 'FWD', club: 'Pau FC' },
        { name: 'Ronaldo Dieu', number: 9, position: 'FWD', club: 'Don Bosco FC' },
      ],
      subs: [
        { name: 'Jhony Placide', number: 12, position: 'GK', club: 'Valencia' },
        { name: 'Jonathan Pétion', number: 13, position: 'DEF', club: 'Joventut Mahonesa' },
        { name: 'Jeff Louis', number: 14, position: 'DEF', club: 'Don Bosco FC' },
        { name: 'Kevin Lafrance', number: 15, position: 'MID', club: 'Cibao FC' },
        { name: 'Jean Wilderson Guerrier', number: 16, position: 'MID', club: 'AS Capoise' },
        { name: 'Carlens Arcus', number: 17, position: 'FWD', club: 'Excelsior Rotterdam' },
        { name: 'Bernier Célestin', number: 18, position: 'FWD', club: 'Cibao FC' },
      ],
    },
  },

  'fifwc-esp-ksa-2026-06-21': {
    home: {
      starters: [
        { name: 'Unai Simón', number: 1, position: 'GK', club: 'Athletic Club' },
        { name: 'Pedro Porro', number: 2, position: 'DEF', club: 'Tottenham' },
        { name: 'Pau Cubarsí', number: 4, position: 'DEF', club: 'Barcelona' },
        { name: 'Aymeric Laporte', number: 5, position: 'DEF', club: 'Athletic Club' },
        { name: 'Marc Cucurella', number: 19, position: 'DEF', club: 'Chelsea' },
        { name: 'Rodri', number: 14, position: 'MID', club: 'Manchester City' },
        { name: 'Pedri', number: 7, position: 'MID', club: 'Barcelona' },
        { name: 'Fabián Ruiz', number: 8, position: 'MID', club: 'PSG' },
        { name: 'Lamine Yamal', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Dani Olmo', number: 10, position: 'FWD', club: 'Barcelona' },
        { name: 'Nico Williams', number: 17, position: 'FWD', club: 'Athletic Club' },
      ],
      subs: [
        { name: 'David Raya', number: 12, position: 'GK', club: 'Arsenal' },
        { name: 'Joan García', number: 23, position: 'GK', club: 'Barcelona' },
        { name: 'Alejandro Grimaldo', number: 3, position: 'DEF', club: 'Bayer Leverkusen' },
        { name: 'Eric García', number: 16, position: 'DEF', club: 'Barcelona' },
        { name: 'Marcos Llorente', number: 6, position: 'DEF', club: 'Atlético Madrid' },
        { name: 'Gavi', number: 9, position: 'MID', club: 'Barcelona' },
        { name: 'Mikel Merino', number: 15, position: 'MID', club: 'Arsenal' },
        { name: 'Alex Baena', number: 22, position: 'MID', club: 'Atlético Madrid' },
        { name: 'Mikel Oyarzabal', number: 13, position: 'FWD', club: 'Real Sociedad' },
        { name: 'Ferran Torres', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Yeremy Pino', number: 25, position: 'FWD', club: 'Crystal Palace' },
      ],
    },
    away: {
      starters: [
        { name: 'Mohammed Al-Owais', number: 1, position: 'GK', club: 'Al-Hilal' },
        { name: 'Saud Abdulhamid', number: 2, position: 'DEF', club: 'AS Roma' },
        { name: 'Ali Al-Bulayhi', number: 5, position: 'DEF', club: 'Al-Hilal' },
        { name: 'Abdulelah Al-Amri', number: 6, position: 'DEF', club: 'Al-Hilal' },
        { name: 'Yasser Al-Shahrani', number: 3, position: 'DEF', club: 'Al-Hilal' },
        { name: 'Abdullah Otayf', number: 7, position: 'MID', club: 'Al-Hilal' },
        { name: 'Sami Al-Najei', number: 8, position: 'MID', club: 'Al-Ittihad' },
        { name: 'Salem Al-Dawsari', number: 10, position: 'MID', club: 'Al-Hilal' },
        { name: 'Abdulrahman Ghareeb', number: 11, position: 'FWD', club: 'Al-Hilal' },
        { name: 'Firas Al-Buraikan', number: 9, position: 'FWD', club: 'Al-Fateh' },
        { name: 'Abdullah Al-Hamdan', number: 20, position: 'FWD', club: 'Al-Shabab' },
      ],
      subs: [
        { name: 'Nawaf Al-Aqidi', number: 12, position: 'GK', club: 'Al-Qadsiah' },
        { name: 'Mohammed Al-Rubaie', number: 23, position: 'GK', club: 'Al-Qadsiah' },
        { name: 'Mohammed Alburayk', number: 13, position: 'DEF', club: 'Al-Hilal' },
        { name: 'Hassan Tambakti', number: 4, position: 'DEF', club: 'Al-Shabab' },
        { name: 'Mohammed Al-Breik', number: 14, position: 'DEF', club: 'Al-Hilal' },
        { name: 'Nasser Al-Dawsari', number: 15, position: 'MID', club: 'Al-Hilal' },
        { name: 'Hattan Bahebri', number: 16, position: 'MID', club: 'Al-Shabab' },
        { name: 'Riyadh Sharahili', number: 17, position: 'MID', club: 'Al-Ettifaq' },
        { name: 'Saleh Al-Shehri', number: 18, position: 'FWD', club: 'Al-Ittihad' },
        { name: 'Ali Al-Hassan', number: 19, position: 'FWD', club: 'Al-Ittihad' },
      ],
    },
  },

  'fifwc-eng-gha-2026-06-23': {
    home: {
      starters: [
        { name: 'Jordan Pickford', number: 1, position: 'GK', club: 'Everton' },
        { name: 'Reece James', number: 2, position: 'DEF', club: 'Chelsea' },
        { name: 'John Stones', number: 4, position: 'DEF', club: 'Manchester City' },
        { name: 'Marc Guéhi', number: 5, position: 'DEF', club: 'Manchester City' },
        { name: 'Tino Livramento', number: 22, position: 'DEF', club: 'Newcastle United' },
        { name: 'Declan Rice', number: 8, position: 'MID', club: 'Arsenal' },
        { name: 'Kobbie Mainoo', number: 14, position: 'MID', club: 'Manchester United' },
        { name: 'Bukayo Saka', number: 11, position: 'FWD', club: 'Arsenal' },
        { name: 'Jude Bellingham', number: 7, position: 'MID', club: 'Real Madrid' },
        { name: 'Marcus Rashford', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Harry Kane', number: 9, position: 'FWD', club: 'Bayern Munich' },
      ],
      subs: [
        { name: 'Dean Henderson', number: 12, position: 'GK', club: 'Crystal Palace' },
        { name: 'James Trafford', number: 23, position: 'GK', club: 'Manchester City' },
        { name: 'Dan Burn', number: 3, position: 'DEF', club: 'Newcastle United' },
        { name: 'Ezri Konsa', number: 6, position: 'DEF', club: 'Aston Villa' },
        { name: 'Djed Spence', number: 16, position: 'DEF', club: 'Tottenham' },
        { name: 'Eberechi Eze', number: 10, position: 'MID', club: 'Arsenal' },
        { name: 'Elliot Anderson', number: 15, position: 'MID', club: 'Nottingham Forest' },
        { name: 'Morgan Rogers', number: 20, position: 'MID', club: 'Aston Villa' },
        { name: 'Ollie Watkins', number: 21, position: 'FWD', club: 'Aston Villa' },
        { name: 'Anthony Gordon', number: 25, position: 'FWD', club: 'Barcelona' },
        { name: 'Ivan Toney', number: 24, position: 'FWD', club: 'Al Ahli' },
      ],
    },
    away: {
      starters: [
        { name: 'Lawrence Ati-Zigi', number: 1, position: 'GK', club: 'St. Gallen' },
        { name: 'Tariq Lamptey', number: 2, position: 'DEF', club: 'Brighton' },
        { name: 'Alexander Djiku', number: 4, position: 'DEF', club: 'Fenerbahçe' },
        { name: 'Daniel Amartey', number: 5, position: 'DEF', club: 'Leicester City' },
        { name: 'Gideon Mensah', number: 3, position: 'DEF', club: 'Red Bull Salzburg' },
        { name: 'Thomas Partey', number: 6, position: 'MID', club: 'Arsenal' },
        { name: 'Salis Abdul Samed', number: 8, position: 'MID', club: 'Lens' },
        { name: 'Mohammed Kudus', number: 10, position: 'MID', club: 'West Ham' },
        { name: 'Antoine Semenyo', number: 7, position: 'FWD', club: 'Bournemouth' },
        { name: 'Jordan Ayew', number: 9, position: 'FWD', club: 'Crystal Palace' },
        { name: 'Joseph Paintsil', number: 11, position: 'FWD', club: 'LA Galaxy' },
      ],
      subs: [
        { name: 'Abdul Manaf Nurudeen', number: 12, position: 'GK', club: 'Eupen' },
        { name: 'Danlad Ibrahim', number: 23, position: 'GK', club: 'Asante Kotoko' },
        { name: 'Denis Odoi', number: 13, position: 'DEF', club: 'Club Brugge' },
        { name: 'Alidu Seidu', number: 14, position: 'DEF', club: 'Clermont Foot' },
        { name: 'Abdul Rahman Baba', number: 15, position: 'DEF', club: 'PAOK' },
        { name: 'Elisha Owusu', number: 16, position: 'MID', club: 'AZ Alkmaar' },
        { name: 'Yaw Yeboah', number: 17, position: 'MID', club: 'Wisla Kraków' },
        { name: 'Kudus Mohammed', number: 18, position: 'MID', club: 'West Ham' },
        { name: 'Osman Bukari', number: 19, position: 'FWD', club: 'Red Star Belgrade' },
        { name: 'Richmond Boakye', number: 20, position: 'FWD', club: 'Ionikos' },
        { name: 'Andy Yiadom', number: 21, position: 'DEF', club: 'Reading' },
      ],
    },
  },

  'fifwc-sco-bra-2026-06-24': {
    home: {
      starters: [
        { name: 'Angus Gunn', number: 1, position: 'GK', club: 'Norwich City' },
        { name: 'Aaron Hickey', number: 2, position: 'DEF', club: 'Brentford' },
        { name: 'Grant Hanley', number: 5, position: 'DEF', club: 'Norwich City' },
        { name: 'Scott McKenna', number: 6, position: 'DEF', club: 'Nottingham Forest' },
        { name: 'Andrew Robertson', number: 3, position: 'DEF', club: 'Liverpool' },
        { name: 'Scott McTominay', number: 8, position: 'MID', club: 'Napoli' },
        { name: 'Callum McGregor', number: 7, position: 'MID', club: 'Celtic' },
        { name: 'Billy Gilmour', number: 10, position: 'MID', club: 'Brighton' },
        { name: 'Ryan Christie', number: 11, position: 'FWD', club: 'Bournemouth' },
        { name: 'Lawrence Shankland', number: 9, position: 'FWD', club: 'Hearts' },
        { name: 'Che Adams', number: 14, position: 'FWD', club: 'Torino' },
      ],
      subs: [
        { name: 'Craig Gordon', number: 12, position: 'GK', club: 'Hearts' },
        { name: 'Liam Kelly', number: 23, position: 'GK', club: 'Motherwell' },
        { name: 'Jack Hendry', number: 4, position: 'DEF', club: 'Al-Ettifaq' },
        { name: 'Liam Cooper', number: 15, position: 'DEF', club: 'Leeds United' },
        { name: 'Anthony Ralston', number: 16, position: 'DEF', club: 'Celtic' },
        { name: 'John McGinn', number: 17, position: 'MID', club: 'Aston Villa' },
        { name: 'Kenny McLean', number: 18, position: 'MID', club: 'Norwich City' },
        { name: 'Lyndon Dykes', number: 19, position: 'FWD', club: 'QPR' },
        { name: 'Stuart Armstrong', number: 20, position: 'MID', club: 'Southampton' },
        { name: 'Oliver Burke', number: 21, position: 'FWD', club: 'Werder Bremen' },
      ],
    },
    away: {
      starters: [
        { name: 'Alisson', number: 1, position: 'GK', club: 'Liverpool' },
        { name: 'Danilo', number: 2, position: 'DEF', club: 'Flamengo' },
        { name: 'Marquinhos', number: 4, position: 'DEF', club: 'PSG' },
        { name: 'Gabriel', number: 5, position: 'DEF', club: 'Arsenal' },
        { name: 'Alex Sandro', number: 3, position: 'DEF', club: 'Flamengo' },
        { name: 'Casemiro', number: 8, position: 'MID', club: 'Manchester United' },
        { name: 'Lucas Paquetá', number: 7, position: 'MID', club: 'Flamengo' },
        { name: 'Raphinha', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Neymar', number: 9, position: 'FWD', club: 'Santos' },
        { name: 'Vinicius Jr.', number: 10, position: 'FWD', club: 'Real Madrid' },
        { name: 'Endrick', number: 24, position: 'FWD', club: 'Real Madrid' },
      ],
      subs: [
        { name: 'Ederson', number: 12, position: 'GK', club: 'Fenerbahçe' },
        { name: 'Weverton', number: 23, position: 'GK', club: 'Grêmio' },
        { name: 'Bremer', number: 6, position: 'DEF', club: 'Juventus' },
        { name: 'Léo Pereira', number: 13, position: 'DEF', club: 'Flamengo' },
        { name: 'Douglas Santos', number: 22, position: 'DEF', club: 'Zenit' },
        { name: 'Bruno Guimarães', number: 16, position: 'MID', club: 'Newcastle United' },
        { name: 'Fabinho', number: 15, position: 'MID', club: 'Al Ittihad' },
        { name: 'Gabriel Martinelli', number: 18, position: 'FWD', club: 'Arsenal' },
        { name: 'Matheus Cunha', number: 20, position: 'FWD', club: 'Manchester United' },
        { name: 'Luiz Henrique', number: 19, position: 'FWD', club: 'Zenit' },
      ],
    },
  },

  'fifwc-tur-usa-2026-06-25': {
    home: {
      starters: [
        { name: 'Mert Günok', number: 1, position: 'GK', club: 'Galatasaray' },
        { name: 'Zeki Çelik', number: 2, position: 'DEF', club: 'AS Roma' },
        { name: 'Merih Demiral', number: 4, position: 'DEF', club: 'Al-Ahli' },
        { name: 'Samet Akaydin', number: 5, position: 'DEF', club: 'Besiktas' },
        { name: 'Ferdi Kadıoğlu', number: 3, position: 'DEF', club: 'Fenerbahçe' },
        { name: 'Hakan Çalhanoğlu', number: 10, position: 'MID', club: 'Inter Milan' },
        { name: 'Kaan Ayhan', number: 8, position: 'MID', club: 'Galatasaray' },
        { name: 'Arda Güler', number: 7, position: 'MID', club: 'Real Madrid' },
        { name: 'Kerem Aktürkoğlu', number: 11, position: 'FWD', club: 'Galatasaray' },
        { name: 'Barış Alper Yılmaz', number: 16, position: 'FWD', club: 'Galatasaray' },
        { name: 'Cenk Tosun', number: 9, position: 'FWD', club: 'Besiktas' },
      ],
      subs: [
        { name: 'Doğan Alemdar', number: 12, position: 'GK', club: 'Lens' },
        { name: 'Altay Bayındır', number: 23, position: 'GK', club: 'Manchester United' },
        { name: 'Abdülkerim Bardakçı', number: 6, position: 'DEF', club: 'Galatasaray' },
        { name: 'Çağlar Söyüncü', number: 14, position: 'DEF', club: 'Fenerbahçe' },
        { name: 'Okay Yokuşlu', number: 15, position: 'MID', club: 'West Brom' },
        { name: 'İrfan Can Kahveci', number: 17, position: 'MID', club: 'Fenerbahçe' },
        { name: 'Salih Özcan', number: 18, position: 'MID', club: 'Borussia Dortmund' },
        { name: 'Yunus Akgün', number: 19, position: 'FWD', club: 'Leicester City' },
        { name: 'Emre Mor', number: 20, position: 'FWD', club: 'Olympiacos' },
        { name: 'Halil Dervişoğlu', number: 21, position: 'FWD', club: 'Besiktas' },
      ],
    },
    away: {
      starters: [
        { name: 'Matt Turner', number: 1, position: 'GK', club: 'New England Revolution' },
        { name: 'Sergino Dest', number: 2, position: 'DEF', club: 'PSV' },
        { name: 'Chris Richards', number: 6, position: 'DEF', club: 'Crystal Palace' },
        { name: 'Miles Robinson', number: 4, position: 'DEF', club: 'FC Cincinnati' },
        { name: 'Antonee Robinson', number: 3, position: 'DEF', club: 'Fulham' },
        { name: 'Tyler Adams', number: 8, position: 'MID', club: 'Bournemouth' },
        { name: 'Weston McKennie', number: 7, position: 'MID', club: 'Juventus' },
        { name: 'Malik Tillman', number: 14, position: 'MID', club: 'Bayer Leverkusen' },
        { name: 'Christian Pulisic', number: 26, position: 'FWD', club: 'AC Milan' },
        { name: 'Gio Reyna', number: 10, position: 'MID', club: 'Borussia Mönchengladbach' },
        { name: 'Folarin Balogun', number: 9, position: 'FWD', club: 'Monaco' },
      ],
      subs: [
        { name: 'Chris Brady', number: 12, position: 'GK', club: 'Chicago Fire' },
        { name: 'Matt Freese', number: 23, position: 'GK', club: 'New York City FC' },
        { name: 'Joe Scally', number: 16, position: 'DEF', club: 'Borussia Mönchengladbach' },
        { name: 'Mark McKenzie', number: 15, position: 'DEF', club: 'Toulouse' },
        { name: 'Auston Trusty', number: 19, position: 'DEF', club: 'Celtic' },
        { name: 'Cristian Roldan', number: 17, position: 'MID', club: 'Seattle Sounders' },
        { name: 'Sebastian Berhalter', number: 22, position: 'MID', club: 'Vancouver Whitecaps' },
        { name: 'Tim Weah', number: 18, position: 'FWD', club: 'Marseille' },
        { name: 'Brenden Aaronson', number: 11, position: 'FWD', club: 'Leeds United' },
        { name: 'Ricardo Pepi', number: 13, position: 'FWD', club: 'PSV' },
        { name: 'Haji Wright', number: 24, position: 'FWD', club: 'Coventry City' },
      ],
    },
  },

  'fifwc-ury-esp-2026-06-26': {
    home: {
      starters: [
        { name: 'Sergio Rochet', number: 1, position: 'GK', club: 'Club Nacional' },
        { name: 'Guillermo Varela', number: 2, position: 'DEF', club: 'Flamengo' },
        { name: 'José María Giménez', number: 4, position: 'DEF', club: 'Atlético Madrid' },
        { name: 'Ronald Araújo', number: 5, position: 'DEF', club: 'Barcelona' },
        { name: 'Mathías Olivera', number: 3, position: 'DEF', club: 'Napoli' },
        { name: 'Lucas Torreira', number: 6, position: 'MID', club: 'Galatasaray' },
        { name: 'Rodrigo Bentancur', number: 8, position: 'MID', club: 'Tottenham' },
        { name: 'Federico Valverde', number: 10, position: 'MID', club: 'Real Madrid' },
        { name: 'Facundo Pellistri', number: 7, position: 'FWD', club: 'Panathinaikos' },
        { name: 'Darwin Núñez', number: 9, position: 'FWD', club: 'Liverpool' },
        { name: 'Agustín Canobbio', number: 11, position: 'FWD', club: 'Athletico Paranaense' },
      ],
      subs: [
        { name: 'Fernando Muslera', number: 12, position: 'GK', club: 'Galatasaray' },
        { name: 'Sebastián Sosa', number: 23, position: 'GK', club: 'Independiente' },
        { name: 'Diego Godín', number: 13, position: 'DEF', club: 'Independiente' },
        { name: 'Nahitan Nández', number: 14, position: 'DEF', club: 'Cagliari' },
        { name: 'Matías Viña', number: 15, position: 'DEF', club: 'AS Roma' },
        { name: 'Giorgian De Arrascaeta', number: 16, position: 'MID', club: 'Flamengo' },
        { name: 'Manuel Ugarte', number: 17, position: 'MID', club: 'Manchester United' },
        { name: 'Nicolás De La Cruz', number: 18, position: 'MID', club: 'Flamengo' },
        { name: 'Maxi Gómez', number: 19, position: 'FWD', club: 'Celta Vigo' },
        { name: 'Edinson Cavani', number: 21, position: 'FWD', club: 'Boca Juniors' },
      ],
    },
    away: {
      starters: [
        { name: 'Unai Simón', number: 1, position: 'GK', club: 'Athletic Club' },
        { name: 'Pedro Porro', number: 2, position: 'DEF', club: 'Tottenham' },
        { name: 'Pau Cubarsí', number: 4, position: 'DEF', club: 'Barcelona' },
        { name: 'Aymeric Laporte', number: 5, position: 'DEF', club: 'Athletic Club' },
        { name: 'Marc Cucurella', number: 19, position: 'DEF', club: 'Chelsea' },
        { name: 'Rodri', number: 14, position: 'MID', club: 'Manchester City' },
        { name: 'Pedri', number: 7, position: 'MID', club: 'Barcelona' },
        { name: 'Fabián Ruiz', number: 8, position: 'MID', club: 'PSG' },
        { name: 'Lamine Yamal', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Dani Olmo', number: 10, position: 'FWD', club: 'Barcelona' },
        { name: 'Nico Williams', number: 17, position: 'FWD', club: 'Athletic Club' },
      ],
      subs: [
        { name: 'David Raya', number: 12, position: 'GK', club: 'Arsenal' },
        { name: 'Joan García', number: 23, position: 'GK', club: 'Barcelona' },
        { name: 'Alejandro Grimaldo', number: 3, position: 'DEF', club: 'Bayer Leverkusen' },
        { name: 'Eric García', number: 16, position: 'DEF', club: 'Barcelona' },
        { name: 'Marcos Llorente', number: 6, position: 'DEF', club: 'Atlético Madrid' },
        { name: 'Gavi', number: 9, position: 'MID', club: 'Barcelona' },
        { name: 'Mikel Merino', number: 15, position: 'MID', club: 'Arsenal' },
        { name: 'Martin Zubimendi', number: 20, position: 'MID', club: 'Arsenal' },
        { name: 'Mikel Oyarzabal', number: 13, position: 'FWD', club: 'Real Sociedad' },
        { name: 'Ferran Torres', number: 11, position: 'FWD', club: 'Barcelona' },
        { name: 'Alex Baena', number: 22, position: 'MID', club: 'Atlético Madrid' },
      ],
    },
  },

  'fifwc-pan-eng-2026-06-27': {
    home: {
      starters: [
        { name: 'Luis Mejía', number: 1, position: 'GK', club: 'Independiente' },
        { name: 'Fidel Escobar', number: 4, position: 'DEF', club: 'New England Revolution' },
        { name: 'Erick Davis', number: 5, position: 'DEF', club: 'Mazatlán FC' },
        { name: 'Roderick Miller', number: 3, position: 'DEF', club: 'FK Rostov' },
        { name: 'Harold Cummings', number: 2, position: 'DEF', club: 'New York City FC' },
        { name: 'Aníbal Godoy', number: 6, position: 'MID', club: 'Nashville SC' },
        { name: 'Adalberto Carrasquilla', number: 8, position: 'MID', club: 'Granada' },
        { name: 'Édgar Yoel Bárcenas', number: 11, position: 'FWD', club: 'Girona' },
        { name: 'Rolando Blackburn', number: 7, position: 'FWD', club: 'Independiente' },
        { name: 'Ismael Díaz', number: 10, position: 'FWD', club: 'Paris FC' },
        { name: 'Abdiel Ayarza', number: 9, position: 'FWD', club: 'Sporting KC' },
      ],
      subs: [
        { name: 'Orlando Mosquera', number: 12, position: 'GK', club: 'Deportivo Cali' },
        { name: 'Jaime Penedo', number: 23, position: 'GK', club: 'Olimpia' },
        { name: 'Eric Archbold', number: 13, position: 'DEF', club: 'Independiente' },
        { name: 'César Yanis', number: 14, position: 'DEF', club: 'Dep. Árabe Unido' },
        { name: 'Ricardo Ávila', number: 15, position: 'MID', club: 'Arabe Unido' },
        { name: 'Jovani Welch', number: 16, position: 'MID', club: 'New England Revolution' },
        { name: 'Alberto Quintero', number: 17, position: 'FWD', club: 'Olimpia' },
        { name: 'Cecilio Waterman', number: 18, position: 'FWD', club: 'CS Emelec' },
        { name: 'Gabriel Torres', number: 19, position: 'FWD', club: 'CD Árabe Unido' },
      ],
    },
    away: {
      starters: [
        { name: 'Jordan Pickford', number: 1, position: 'GK', club: 'Everton' },
        { name: 'Reece James', number: 2, position: 'DEF', club: 'Chelsea' },
        { name: 'John Stones', number: 4, position: 'DEF', club: 'Manchester City' },
        { name: 'Marc Guéhi', number: 5, position: 'DEF', club: 'Manchester City' },
        { name: 'Tino Livramento', number: 22, position: 'DEF', club: 'Newcastle United' },
        { name: 'Declan Rice', number: 8, position: 'MID', club: 'Arsenal' },
        { name: 'Kobbie Mainoo', number: 14, position: 'MID', club: 'Manchester United' },
        { name: 'Bukayo Saka', number: 11, position: 'FWD', club: 'Arsenal' },
        { name: 'Jude Bellingham', number: 7, position: 'MID', club: 'Real Madrid' },
        { name: 'Marcus Rashford', number: 18, position: 'FWD', club: 'Barcelona' },
        { name: 'Harry Kane', number: 9, position: 'FWD', club: 'Bayern Munich' },
      ],
      subs: [
        { name: 'Dean Henderson', number: 12, position: 'GK', club: 'Crystal Palace' },
        { name: 'James Trafford', number: 23, position: 'GK', club: 'Manchester City' },
        { name: 'Dan Burn', number: 3, position: 'DEF', club: 'Newcastle United' },
        { name: 'Ezri Konsa', number: 6, position: 'DEF', club: 'Aston Villa' },
        { name: 'Djed Spence', number: 16, position: 'DEF', club: 'Tottenham' },
        { name: 'Eberechi Eze', number: 10, position: 'MID', club: 'Arsenal' },
        { name: 'Elliot Anderson', number: 15, position: 'MID', club: 'Nottingham Forest' },
        { name: 'Morgan Rogers', number: 20, position: 'MID', club: 'Aston Villa' },
        { name: 'Ollie Watkins', number: 21, position: 'FWD', club: 'Aston Villa' },
        { name: 'Anthony Gordon', number: 25, position: 'FWD', club: 'Barcelona' },
        { name: 'Ivan Toney', number: 24, position: 'FWD', club: 'Al Ahli' },
      ],
    },
  },
};
